/**
 * Mapping between Minecraft 1.16.1 potion effect IDs and texture variant numbers
 * Based on the order of textures generated by mc-texture-renderer
 */

export const POTION_EFFECT_TO_TEXTURE: Record<string, number> = {
  // Water bottle / Mundane potions
  'minecraft:water': 1,
  'minecraft:mundane': 2,
  'minecraft:thick': 3,
  'minecraft:awkward': 4,

  // Night Vision
  'minecraft:night_vision': 5,
  'minecraft:long_night_vision': 6,

  // Invisibility
  'minecraft:invisibility': 7,
  'minecraft:long_invisibility': 8,

  // Leaping / Jump Boost
  'minecraft:leaping': 9,
  'minecraft:long_leaping': 10,
  'minecraft:strong_leaping': 11,

  // Fire Resistance
  'minecraft:fire_resistance': 12,
  'minecraft:long_fire_resistance': 13,

  // Swiftness / Speed
  'minecraft:swiftness': 14,
  'minecraft:long_swiftness': 15,
  'minecraft:strong_swiftness': 16,

  // Slowness
  'minecraft:slowness': 17,
  'minecraft:long_slowness': 18,
  'minecraft:strong_slowness': 19,

  // Turtle Master
  'minecraft:turtle_master': 20,
  'minecraft:long_turtle_master': 21,
  'minecraft:strong_turtle_master': 22,

  // Water Breathing
  'minecraft:water_breathing': 23,
  'minecraft:long_water_breathing': 24,

  // Healing / Instant Health
  'minecraft:healing': 25,
  'minecraft:strong_healing': 26,

  // Harming / Instant Damage
  'minecraft:harming': 27,
  'minecraft:strong_harming': 28,

  // Poison
  'minecraft:poison': 29,
  'minecraft:long_poison': 30,
  'minecraft:strong_poison': 31,

  // Regeneration
  'minecraft:regeneration': 32,
  'minecraft:long_regeneration': 33,
  'minecraft:strong_regeneration': 34,

  // Strength
  'minecraft:strength': 35,
  'minecraft:long_strength': 36,
  'minecraft:strong_strength': 37,

  // Weakness
  'minecraft:weakness': 38,
  'minecraft:long_weakness': 39,

  // Slow Falling
  'minecraft:slow_falling': 40,
  'minecraft:long_slow_falling': 41,
};

/**
 * Get the texture variant number for a potion effect
 * Returns undefined if the effect is not found
 */
export function getPotionTextureVariant(potionEffect: string | undefined): number | undefined {
  if (!potionEffect) return undefined;
  return POTION_EFFECT_TO_TEXTURE[potionEffect];
}
